# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-git_requehub-actions
name: CI
on: [push,pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v2
      - name: Using Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup PostgreSQL
        uses: actions/checkout@v2
        with:
          postgresql version: 11
          postgresql db: sangini_test
          postgresql user: postgres
          postgresql port: 5432
          postgresql password: 1234

      - run: npm install
      - run: npm test
